### Data analysis

* Data :data is facts and statistics collected together for reference or analysis
* Data analysis:
    * is a process of obtaining raw data and subsequently converting it into information,useful for decision making
    * is a technique to collect , transform and organize data to make future predictions
    * all sorts of data analysis,Analyzing the numerical data with numpy,tabular data with pandas 
    and visualization by matplotlib and exploratory data analysis

### Data Collection

* Primary data: 
    * refers to first hand data generated by the research himself/herself
    * real time data
    * Surveys, Observations,experiments,questionanaire,personal interviews etc
    * Expensive and takes long time
    
* Secondary data:
    * data which is collected by someone else earlier
    * Past data
    * Websites, books, journals,articles, internal records, government publications etc
    * Economical and takes short time

### Types of data

* Structured data: row/columns -> tabular format -> excel file,.csv,.tsv etc
* Unstructured data: pictures,videos,text,.ppt,.pdf,log files ,voices
* Semi structured data: xml,json,html files {key:value}

### Data types in statistics

* Numerical data: data in the form of numbers
    *1.Discrete data: 
        * is a count that involves only integers. can't be subdivided into parts
        * ex: no of students in a class
        * no of workers in a company etc
        
    *2.Continuous data:
        * Continuous data could be meaniningfully divided into finger levels
        * It can be measured on a scale & have a numerical value
        * ex: height,weight of a children etc..
        
* Categorical data: made of words
* 1.Nominal data
                * nominal data is used for labelling variables
                * Ex: Gender(male,female)
* 2.Ordinal data
                * Ordinal data is data which is placed into some kind of order by their position on a scale
                * Ex: 1st ,2nd,3rd persons in a competition





### Numpy  - Numerical python
* It is a open source python library
* It is used for scientific computing and working with arrays
* Numpy provides high level functioning tools to works with arrays
* Using numpy we can perform both logical and mathematical operations on arrays
* It also has functions in domain of Linear algebra,fourier transforms and matrices

In [2]:
l=[10,20,30,40,50]
l+10

TypeError: can only concatenate list (not "int") to list

In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

In [5]:
# creating array using numpy

l=[10,20,30,40,50]
ar=np.array(l)
print(ar)
print(type(ar))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
ar+10    # in arrays elements wise operation is possible

array([20, 30, 40, 50, 60])

In [7]:
print(ar.ndim)  # no of dimensional
print(ar.size)  # size of an array
print(ar.itemsize)  # itemsize of an array
print(max(ar))  # maximum value of an array
print(min(ar))   # minimum value of an array

1
5
4
50
10


In [8]:
ar+100

array([110, 120, 130, 140, 150])