### Numpy

In [1]:
import numpy as np

In [2]:
l=[10,20,30,40,50]
ar=np.array(l)
ar

array([10, 20, 30, 40, 50])

In [3]:
print(ar.size)

5


In [4]:
a1=np.array([10,20,30],dtype="complex")
a1

array([10.+0.j, 20.+0.j, 30.+0.j])

In [5]:
a1.ndim

1

In [6]:
a2=np.array([10,20,30],ndmin=2)
a2

array([[10, 20, 30]])

In [7]:
a2.ndim

2

In [9]:
dir(np.dtype)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

In [10]:
np.array([78,45])

array([78, 45])

In [11]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [12]:
np.array(range(9))

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### range() and arange()

* main difference between these two is range() is a builtin function in python, whereas arange belongs to numpy

In [14]:
# arange() -> belongs to numpy

a1=np.arange(11,21)
print(a1)
print(np.arange(5))
print(np.arange(4,1))
print(np.arange(1,10))

[11 12 13 14 15 16 17 18 19 20]
[0 1 2 3 4]
[]
[1 2 3 4 5 6 7 8 9]


In [15]:
b=np.array(range(1,100,2))
print(b)
print(type(b))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
<class 'numpy.ndarray'>


In [16]:
c=np.arange(1,100,2)
print(c)
print(type(c))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
<class 'numpy.ndarray'>


In [17]:
c+5

array([  6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,
        32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,
        58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
        84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104])

In [19]:
a=np.arange(25)
print(a)
print(a.ndim)
b=a.reshape(5,5)
print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2


In [21]:
for i in a:
    print(i,end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

### Linspace()

* returns no of spaces evenly w.r.to intervals
* similar to arange(), instead of step it uses sample number

In [22]:
a=np.linspace(1,20,4)
print(a)
print(type(a))

[ 1.          7.33333333 13.66666667 20.        ]
<class 'numpy.ndarray'>


### Array Initialization

* ones() returns a new array of given shape and type, with ones
* bydefault datatype float

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
b=np.ones([2,2],dtype=int)
b

array([[1, 1],
       [1, 1]])

In [28]:
np.ones((3,2,1))

array([[[1.],
        [1.]],

       [[1.],
        [1.]],

       [[1.],
        [1.]]])

In [29]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros(9,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [32]:
np.full([2,2],45)   # returns 2*2 array filled with value 45

array([[45, 45],
       [45, 45]])

In [33]:
np.empty(9)    # with random values

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 5.13828272e-321, 3.11525958e-307, 1.24610723e-306,
       0.00000000e+000])

In [35]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.13828272e-321],
       [3.11525958e-307, 1.24610723e-306, 0.00000000e+000]])

In [36]:
np.empty(15,dtype="complex")

array([6.60072698e-312+6.60029020e-312j, 0.00000000e+000+0.00000000e+000j,
       8.34674312e-309+1.16097020e-028j, 1.26104862e-076+2.42245817e-028j,
       3.30884676e-033+1.04917183e-153j, 5.23081515e-143+8.24173005e-043j,
       3.69785518e-057+2.09029434e-076j, 3.37996278e-061+1.70098498e+256j,
       5.49109388e-143+1.06396443e+224j, 3.96041428e+246+1.16318408e-028j,
       2.04047762e+184+3.89036969e-033j, 9.22794231e-071+1.65716969e-047j,
       1.01848862e+248+1.16096643e-028j, 9.80058441e+252+7.50189709e+247j,
       1.14484251e+243+2.59903827e-144j])

###  eye() 
* create 2D array with 1's on diagonal and 0's elsewhere

In [37]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,k=1)  # k=1 upper diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [40]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [41]:
np.diag([3,4,5])

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [43]:
## array elements accessing - 1D


a=np.array([10,20,30,40,50])
print(a[0])
print(a[0]+a[1])

10
30


In [44]:
print(a[-1])

50


In [45]:
#  creating and accessing 2D array

l1=[1,2,3]
l2=[4,5,6]
b=np.array([l1,l2])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# to get 2nd row 2nd index element

b[1,2]

6

In [47]:
# get value 5 from array b

b[1,1]

5