In [1]:
# creating 3D array

import numpy as np

c=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])
print(c)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [2]:
c[0]

array([[10, 20],
       [30, 40]])

In [3]:
c[1]

array([[50, 60],
       [70, 80]])

In [4]:
# to get value 70

c[1,1,0]

70

In [5]:
# TO get value 60

c[1,0,1]

60

In [7]:
# slicing in arrays   [start:end:step]

a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [8]:
a[0::2]

array([10, 30, 50])

In [9]:
a[1:3]

array([20, 30])

In [ ]:
# access 20,40
# access 20,30,40 and print sum also

In [11]:
b=np.array([[10,20,80],[30,40,70]])
b

array([[10, 20, 80],
       [30, 40, 70]])

In [14]:
# to get values from 1st row, col index 1...

b[0,1:]

array([20, 80])

In [15]:
# 30,40,70

b[1,:]

array([30, 40, 70])

In [16]:
c

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [17]:
c[::-1]

array([[[50, 60],
        [70, 80]],

       [[10, 20],
        [30, 40]]])

In [18]:
a=np.full([2,2],3)
a

array([[3, 3],
       [3, 3]])

In [19]:
a[0][0]=5  #changing array value
print(a)

[[5 3]
 [3 3]]


### random

* Python has built-in module that you can use to make random numbers
* random() returns a random float number between 0 and 1


In [25]:
print(np.random.random())
print(np.random.randint(5))
print(np.random.randint(1,1000,6))
print(np.random.randint(1,50,(2,3)))

0.6694653955541143
4
[879 914 703 619 947 221]
[[49 47 26]
 [18 42 26]]


In [28]:
# stacking

# horizontal stacking

a=np.array([1,2,3])
b=np.array([4,5,6])
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [29]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# fancy indexing or boolean indexing

a=np.random.randint(1,100,12)
a

array([ 5, 60, 16, 26, 54, 46,  7, 30, 60, 73, 57, 33])

In [33]:
a>50

array([False,  True, False, False,  True, False, False, False,  True,
        True,  True, False])

In [34]:
(a>50).sum()

5

In [35]:
a[a>50]   # fancy indexing

array([60, 54, 60, 73, 57])

In [36]:
(a>50)  & (a<80)

array([False,  True, False, False,  True, False, False, False,  True,
        True,  True, False])

In [37]:
a[(a>50)  & (a<80)]

array([60, 54, 60, 73, 57])

In [38]:
# array manipulation

a=np.arange(32)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [39]:
a.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [40]:
a.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
a.reshape(16,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31]])

In [42]:
a.reshape(2,16)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [43]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [44]:
a.reshape(-1,8)  # 2D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [45]:
a.reshape(4,4,2)  #3D array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]]])

In [47]:
a.reshape(8,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]]])

In [48]:
a=np.arange(1,4)
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [52]:
# mathematical operations on arrays

print(a+b)
print(a-b)
print(a*b)  # normal multiplication
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
